#!/usr/bin/env bash
# BookFactory — Series Template Generator
# Creates a new book project with full pipeline structure in seconds.
#
# Usage: bash new-book.sh "Book Title Here" fiction|health|business
# Example: bash new-book.sh "Fix Your Hormones for Good" health

set -e

FACTORY="$(cd "$(dirname "$0")" && pwd)"
BOOKS_DIR="$FACTORY/books"

TITLE="$1"
GENRE="$2"

if [ -z "$TITLE" ] || [ -z "$GENRE" ]; then
  echo ""
  echo "Usage: bash new-book.sh \"Book Title Here\" <genre>"
  echo "Genres: health | fiction | business"
  echo ""
  echo "Example: bash new-book.sh \"Fix Your Hormones for Good\" health"
  echo ""
  exit 1
fi

# Slugify title
SLUG=$(echo "$TITLE" | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g' | sed 's/[^a-z0-9-]//g')
BOOK_DIR="$BOOKS_DIR/$SLUG"

if [ -d "$BOOK_DIR" ]; then
  echo "Error: Book folder already exists at $BOOK_DIR"
  exit 1
fi

echo ""
echo "  Creating new book: $TITLE"
echo "  Folder: $SLUG"
echo "  Genre: $GENRE"
echo ""

# ── Create folder structure ──
mkdir -p "$BOOK_DIR/manuscript/handoffs"
mkdir -p "$BOOK_DIR/exports"

# ── Create BLUEPRINT.md stub ──
cat > "$BOOK_DIR/BLUEPRINT.md" << BLUEPRINTSTUB
# $TITLE — Blueprint

---

## BOOK IDENTITY

**Title:** $TITLE
**Subtitle:** *(run book-architect to generate)*
**Genre:** $(echo "$GENRE" | awk '{print toupper(substr($0,1,1))substr($0,2)}')
**Voice:** *(define after architect runs)*
**Comparables:** *(3 comps)*
**Tone:** *(define)*

**Target word count:** *(set after architect runs)*

---

## THE PREMISE

*(Run: architect "$TITLE" to generate full blueprint)*

---

## CHAPTER OUTLINE

| File | Chapter | Status |
|------|---------|--------|
| 00-introduction.md | Introduction | ⬜ Not started |

*Full outline to be generated by book-architect agent.*

---

## CHAPTER STATUS

*(Updated by build-pdf.sh on each build)*
BLUEPRINTSTUB

# ── Create FACTS.md ──
cat > "$BOOK_DIR/FACTS.md" << FACTSSTUB
# $TITLE — Continuity Bible
## FACTS.md

---

## STATISTICS LOCKED IN

| Stat | Value | Source | Chapter |
|------|-------|---------|---------|

---

## MEDICAL/TECHNICAL TERMS DEFINED

| Term | Definition | First used in |
|------|-----------|---------------|

---

## PROMISES MADE TO THE READER

| Promise | Made in | Delivers in |
|---------|---------|-------------|

---

## VOICE ANCHORS

- Target reader: *(define)*
- Tone anchor: *(define)*
- Mirror sentence: *(first one added here after Ch. 1)*

---

## CHAPTER HANDOFF BRIEFS

*(Added after each approved chapter)*
FACTSSTUB

# ── Placeholder introduction ──
cat > "$BOOK_DIR/manuscript/00-introduction.md" << INTROSTUB
# Introduction
## *(Subtitle — generated by health-writer/fiction-writer/business-writer)*

*(Write: write chapter intro $GENRE)*
INTROSTUB

# ── Update PIPELINE.md ──
PIPELINE="$FACTORY/PIPELINE.md"

# Add to ACTIVE BOOKS table
if grep -q "| $TITLE |" "$PIPELINE" 2>/dev/null; then
  echo "  ℹ Book already listed in PIPELINE.md"
else
  # Insert before the closing --- of the ACTIVE BOOKS table
  # Use Python for reliable multiline sed on Windows bash
  python3 -c "
import re, sys
content = open('$PIPELINE').read()
new_row = '| $TITLE | $(echo "$GENRE" | awk \"{print toupper(substr(\$0,1,1))substr(\$0,2)}\") | ⬜ Pending | 0 | Run architect |'
# Find the active books table and append before the last ---
content = content.replace(
  '---\n\n## FOLDER STRUCTURE',
  new_row + '\n---\n\n## FOLDER STRUCTURE'
)
open('$PIPELINE', 'w').write(content)
" 2>/dev/null || echo "  ⚠ Could not auto-update PIPELINE.md — add manually."
fi

echo "  ✓ Folder structure created at: $BOOK_DIR"
echo ""
echo "  Next steps:"
echo "  1. Run: architect \"$TITLE\""
echo "     → Generates full blueprint, chapter outline, tone bible"
echo "  2. Run: write chapter intro $GENRE"
echo "     → Drafts the introduction"
echo "  3. Run: bash build-pdf.sh $SLUG"
echo "     → Generates PDF"
echo ""
