/**
 * Queue processor — intake layer for the BookFactory pipeline.
 *
 * Reads books/.queue.json and handles each entry lifecycle:
 *
 *   pending        → bootstraps the book folder + pipeline-state.json,
 *                    sets status to "researching"
 *                    (the per-book loop then runs stage-1 research agents)
 *
 *   researching    → no action needed; the per-book loop drives stage 1.
 *                    Once current_stage advances to 2, the existing
 *                    market_intelligence_approved gate blocks automatically
 *                    and NOTIFICATIONS.md tells the user to review the brief.
 *
 *   approved       → sets human_gates.market_intelligence_approved = true
 *                    in the book's pipeline-state.json so stage 2 unlocks,
 *                    then marks the entry "in_pipeline"
 *
 *   rejected       → marks entry "archived"; pipeline never runs for it
 *
 *   in_pipeline    → nothing to do; per-book loop handles it
 *   archived       → nothing to do
 */
import fs from "node:fs/promises";
import crypto from "node:crypto";
import path from "node:path";
import type { DaemonConfig, QueueEntry, QueueFile } from "./types.js";
import { appendActivityEntry } from "./notifications.js";

// ── File I/O ────────────────────────────────────────────────────────────────

export async function readQueue(queueFile: string): Promise<QueueFile> {
  try {
    const raw = await fs.readFile(queueFile, "utf8");
    return JSON.parse(raw) as QueueFile;
  } catch {
    return { entries: [] };
  }
}

export async function writeQueue(
  queueFile: string,
  queue: QueueFile
): Promise<void> {
  await fs.writeFile(queueFile, JSON.stringify(queue, null, 2) + "\n", "utf8");
}

// ── Helpers ─────────────────────────────────────────────────────────────────

export function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

function genreCode(genre: string): string {
  const map: Record<string, string> = {
    health:   "NON-FICTION-HEALTH",
    business: "NON-FICTION-BUSINESS",
    fiction:  "FICTION-GENERAL",
    mystery:  "FICTION-MYSTERY",
    fantasy:  "FICTION-FANTASY",
    thriller: "FICTION-THRILLER",
    romance:  "FICTION-ROMANCE",
    scifi:    "FICTION-SCIFI",
  };
  return map[genre.toLowerCase()] ?? genre.toUpperCase();
}

async function fileExists(p: string): Promise<boolean> {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

// ── Book bootstrapping ──────────────────────────────────────────────────────

export async function bootstrapBook(
  entry: QueueEntry,
  bookfactoryRoot: string
): Promise<void> {
  const slug = entry.slug!;
  const bookDir = path.join(bookfactoryRoot, "books", slug);

  // Directories
  await fs.mkdir(path.join(bookDir, "manuscript", "handoffs"), {
    recursive: true,
  });
  await fs.mkdir(path.join(bookDir, "exports"), { recursive: true });

  // pipeline-state.json from template
  const templatePath = path.join(
    bookfactoryRoot,
    "pipeline-state.template.json"
  );
  const raw = await fs.readFile(templatePath, "utf8");
  const state = JSON.parse(raw);
  state.book_slug = slug;
  state.book_title = entry.title;
  state.genre = genreCode(entry.genre);
  state.current_stage = 1;
  state.last_updated = new Date().toISOString();
  state.agent_log = [
    {
      timestamp: new Date().toISOString(),
      agent: "queue-processor",
      action: `Bootstrapped from queue — niche: "${entry.niche_hint ?? entry.genre}"`,
      result: "in_progress",
      notes: "Stage 1 research will begin on next daemon cycle.",
    },
  ];
  await fs.writeFile(
    path.join(bookDir, "pipeline-state.json"),
    JSON.stringify(state, null, 2) + "\n",
    "utf8"
  );

  // BLUEPRINT.md stub — agents will fill this in properly during stage 2
  await fs.writeFile(
    path.join(bookDir, "BLUEPRINT.md"),
    `# ${entry.title} — Blueprint\n\n` +
      `*Generated by book-architect / novel-writer during stage 2.*\n\n` +
      `**Genre:** ${genreCode(entry.genre)}\n` +
      `**Niche hint:** ${entry.niche_hint ?? entry.genre}\n`,
    "utf8"
  );

  // FACTS.md stub
  await fs.writeFile(
    path.join(bookDir, "FACTS.md"),
    `# ${entry.title} — Continuity Bible\n\n` +
      `*Populated by writer agents during stage 3.*\n`,
    "utf8"
  );
}

// ── Niche approval ──────────────────────────────────────────────────────────

export async function approveNiche(
  slug: string,
  bookfactoryRoot: string,
  now: Date
): Promise<void> {
  const statePath = path.join(
    bookfactoryRoot,
    "books",
    slug,
    "pipeline-state.json"
  );
  const raw = await fs.readFile(statePath, "utf8");
  const state = JSON.parse(raw);
  state.human_gates.market_intelligence_approved = true;
  state.last_updated = now.toISOString();
  if (!Array.isArray(state.agent_log)) state.agent_log = [];
  state.agent_log.push({
    timestamp: now.toISOString(),
    agent: "queue-processor",
    action: "Niche approved by user",
    result: "approved",
    notes: "market_intelligence_approved set to true — stage 2 now unlocked.",
  });
  await fs.writeFile(
    statePath,
    JSON.stringify(state, null, 2) + "\n",
    "utf8"
  );
}

// ── Main entry point ────────────────────────────────────────────────────────

export async function processQueue(
  config: DaemonConfig,
  now: Date
): Promise<void> {
  const queueFile = path.join(config.bookfactoryRoot, "books", ".queue.json");
  const queue = await readQueue(queueFile);

  const actionable = queue.entries.filter((e) =>
    ["pending", "approved", "rejected"].includes(e.status)
  );
  if (actionable.length === 0) return;

  let changed = false;

  for (const entry of queue.entries) {
    // ── pending → researching ──────────────────────────────────────────────
    if (entry.status === "pending") {
      if (!entry.id) entry.id = crypto.randomUUID();
      if (!entry.added_at) entry.added_at = now.toISOString();
      entry.slug = slugify(entry.title);

      const alreadyExists = await fileExists(
        path.join(
          config.bookfactoryRoot,
          "books",
          entry.slug,
          "pipeline-state.json"
        )
      );
      if (!alreadyExists) {
        if (!config.dryRun) {
          await bootstrapBook(entry, config.bookfactoryRoot);
        }
        console.log(
          `[queue] ${config.dryRun ? "DRY RUN — would bootstrap" : "bootstrapped"} "${entry.title}" → books/${entry.slug}`
        );
      }

      entry.status = "researching";
      changed = true;

      await appendActivityEntry(config.activityLogFile, {
        ts: now,
        book: entry.slug,
        action: "queued",
        detail: config.dryRun
          ? `DRY RUN — would bootstrap "${entry.title}"`
          : `Bootstrapped "${entry.title}" — stage-1 research starting`,
      });
    }

    // ── approved → in_pipeline ─────────────────────────────────────────────
    if (entry.status === "approved" && entry.slug) {
      if (!config.dryRun) {
        await approveNiche(entry.slug, config.bookfactoryRoot, now);
      }
      console.log(
        `[queue] ${config.dryRun ? "DRY RUN — would approve" : "approved"} niche for "${entry.title}"`
      );
      entry.status = "in_pipeline";
      if (!entry.approved_at) entry.approved_at = now.toISOString();
      changed = true;

      await appendActivityEntry(config.activityLogFile, {
        ts: now,
        book: entry.slug,
        action: "niche_approved",
        detail: config.dryRun
          ? `DRY RUN — would unlock stage 2 for "${entry.title}"`
          : `Niche approved — stage 2 now unlocked for "${entry.title}"`,
      });
    }

    // ── rejected → archived ────────────────────────────────────────────────
    if (entry.status === "rejected" && entry.slug) {
      console.log(`[queue] archiving rejected idea "${entry.title}"`);
      entry.status = "archived";
      if (!entry.rejected_at) entry.rejected_at = now.toISOString();
      changed = true;

      await appendActivityEntry(config.activityLogFile, {
        ts: now,
        book: entry.slug,
        action: "niche_rejected",
        detail: `"${entry.title}" rejected${entry.reject_reason ? ` — ${entry.reject_reason}` : ""}`,
      });
    }
  }

  if (changed) {
    if (!config.dryRun) {
      await writeQueue(queueFile, queue);
    }
  }
}
